# Voice E-Commerce Ordering — Improved Model

Key improvements over the original notebook:
1. **Raw MFCC + both deltas** (1350 features) — restores base spectral info that was dropped
2. **Conv2d architecture** — reshapes to (3, 30, 15) so convolution learns real spectro-temporal patterns
3. **Class weights in loss** — penalizes confused pairs (1↔5, 2↔4) harder
4. **Learning rate scheduler** — ReduceLROnPlateau avoids overshooting

> **Requires GPU compute.** Switch to Serverless GPU before running.

In [0]:
%pip install torch --extra-index-url https://download.pytorch.org/whl/cpu librosa

Looking in indexes: https://aws:****@utopusinsights-653638594822.d.codeartifact.eu-west-1.amazonaws.com/pypi/scipher/simple/, https://download.pytorch.org/whl/cpu
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 91.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 50.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.9/59.9 MB 82.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.3/196.3 MB 90.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 27.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 70.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 49.7 MB/s eta 0:00:00
  Attempting uninstall: decorator
    Found existing installation: decorator 5.1.1
    Not uninstalling decorator at /databricks/python3/lib/python3.12/site-packages, outside environment /local_disk0/.ephemeral_nfs/envs/pythonEnv-e61f30d1-a73e-42fb-8632-f33817815e68
    Can't unins

In [0]:
from IPython import get_ipython
ipython = get_ipython()
ipython.magic("sx wget -q https://cdn.iiith.talentsprint.com/aiml/Hackathon_data/B17_studio_rev_data.zip")
ipython.magic("sx unzip -qo B17_studio_rev_data.zip")
print("Setup completed successfully")

/home/spark-e61f30d1-a73e-42fb-8632-f3/.ipykernel/89/command-4927068529587983-3681049264:3: DeprecationWarning: `magic(...)` is deprecated since IPython 0.13 (warning added in 8.1), use run_line_magic(magic_name, parameter_s).
  ipython.magic("sx wget -q https://cdn.iiith.talentsprint.com/aiml/Hackathon_data/B17_studio_rev_data.zip")
/home/spark-e61f30d1-a73e-42fb-8632-f3/.ipykernel/89/command-4927068529587983-3681049264:4: DeprecationWarning: `magic(...)` is deprecated since IPython 0.13 (warning added in 8.1), use run_line_magic(magic_name, parameter_s).
  ipython.magic("sx unzip -qo B17_studio_rev_data.zip")


Setup completed successfully


In [0]:
import os, sys, glob, warnings, collections
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import optim
from torch.autograd import Variable
from torch.utils.data import TensorDataset, DataLoader
import librosa
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
warnings.filterwarnings('ignore')

/local_disk0/.ephemeral_nfs/envs/pythonEnv-e61f30d1-a73e-42fb-8632-f33817815e68/lib/python3.12/site-packages/torch/_vmap_internals.py:9: FutureWarning: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
  from torch.utils._pytree import _broadcast_to_and_flatten, tree_flatten, tree_unflatten


In [0]:
import shutil

source_folder = "./studio_data"
dest_folder = "./final_preprocess"
os.makedirs(dest_folder, exist_ok=True)

wrong_files = [
    "5_b18_88.wav","5_b4_100.wav","5_b12_40.wav","2_n_b4_85.wav","3_n_b1_98.wav",
    "2_b18_85.wav","5_n_g6_40.wav","5_n_g23_100.wav","3_G7_26.wav","0_b2_93.wav",
    "5_b18_112.wav","2_n_g15_97.wav","5_b18_16.wav","5_b21_100.wav","5_n_b1_100.wav",
    "5_n_g18_28.wav","2_n_g16_37.wav","4_G8_39.wav","0_n_g6_81.wav","5_n_g18_16.wav",
    "5_n_g5_28.wav","5_n_g10_28.wav","0_n_b7_21.wav","3_G15_2.wav","3_n_g4_26.wav",
    "5_b13_28.wav","5_a1_88.wav","3_n_g22_2.wav","2_n_g21_13.wav","5_G7_4.wav",
    "5_G17_100.wav","5_G7_16.wav","4_n_g20_3.wav","5_b5_4.wav","3_b15_26.wav",
    "4_G7_3.wav","2_b18_61.wav","3_r3_3.wav","5_g42_28.wav","0_b7_57.wav",
    "2_a1_25.wav","5_G14_28.wav","5_b16_52.wav","4_n_b3_99.wav","5_n_g11_28.wav",
    "3_n_g7_26.wav","2_n_g16_109.wav","4_n_g4_75.wav","2_n_g17_25.wav","2_g40_61.wav",
    "5_n_g16_88.wav","5_n_g19_52.wav","4_b2_51.wav","5_b13_52.wav","3_b21_50.wav",
    "5_G14_16.wav","2_n_b4_97.wav","5_g38_40.wav","4_n_g13_51.wav","5_b13_64.wav",
    "3_G17_98.wav","5_b9_64.wav","3_G4_38.wav","4_b9_87.wav","3_n_g8_110.wav",
    "4_b12_75.wav","4_b21_87.wav","0_n_g8_21.wav","4_n_g16_15.wav","5_G7_28.wav",
    "0_b9_21.wav","5_b18_4.wav","5_n_b7_52.wav","3_n_g19_98.wav","5_n_g23_76.wav",
    "5_g42_52.wav","5_b18_52.wav","2_n_g6_73.wav","5_b15_40.wav","4_b12_63.wav",
    "3_n_g10_86.wav","4_b18_15.wav","3_G9_110.wav","4_n_g17_87.wav"
]

moved = sum(1 for f in wrong_files if os.path.exists(os.path.join(source_folder, f))
            and not shutil.move(os.path.join(source_folder, f), os.path.join(dest_folder, f)))
print(f"Moved {moved}/{len(wrong_files)} wrong utterances out of training data")

Moved 0/84 wrong utterances out of training data


In [0]:
# Caution: Do not change the default parameters
def get_features(filepath, sr=8000, n_mfcc=30, n_mels=128, frames=15):
    y, sr = librosa.load(filepath, sr=sr)
    D = np.abs(librosa.stft(y))**2
    S = librosa.feature.melspectrogram(S=D)
    S = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=n_mels)
    log_S = librosa.power_to_db(S, ref=np.max)
    features = librosa.feature.mfcc(S=log_S, n_mfcc=n_mfcc)
    if features.shape[1] < frames:
        features = np.hstack((features, np.zeros((n_mfcc, frames - features.shape[1]))))
    elif features.shape[1] > frames:
        features = features[:, :frames]

    delta1_mfcc = librosa.feature.delta(features, order=1)
    delta2_mfcc = librosa.feature.delta(features, order=2)

    # FIX: Include raw MFCC + both deltas = 30*15*3 = 1350 features
    # Original only used deltas (900) — dropping raw MFCC lost base spectral shape
    combined = np.hstack((features.flatten(), delta1_mfcc.flatten(), delta2_mfcc.flatten()))

    combined = combined.flatten()[:, np.newaxis]
    combined = Variable(torch.from_numpy(combined)).float()
    return combined

In [0]:
def load_data(folder_path):
    features, labels = [], []
    wav_files = glob.glob(os.path.join(folder_path, '*.wav'))
    print(f"Found {len(wav_files)} wav files in {folder_path}")
    for filepath in wav_files:
        filename = os.path.basename(filepath)
        label = int(filename.split('_')[0])
        feat = get_features(filepath)
        features.append(feat.numpy().flatten())   # (1350,)
        labels.append(label)
    return np.array(features), np.array(labels)

In [0]:
# Load features
studio_features, studio_labels = load_data('./studio_data')
print(f"Features: {studio_features.shape}  Labels: {studio_labels.shape}")

# Reshape (N, 1350) -> (N, 3, 30, 15) for Conv2d
# Channel 0 = raw MFCC, Channel 1 = delta1, Channel 2 = delta2
# Each is (30 coefficients, 15 frames)
studio_features_2d = studio_features.reshape(-1, 3, 30, 15)
print(f"Reshaped for Conv2d: {studio_features_2d.shape}")

# Train/test split (stratified)
X_train, X_test, y_train, y_test = train_test_split(
    studio_features_2d, studio_labels,
    test_size=0.2, random_state=42, stratify=studio_labels
)
print(f"Train: {X_train.shape}  Test: {X_test.shape}")

# Class weights — inverse frequency to penalize errors on underrepresented classes
class_counts = np.bincount(y_train, minlength=6)
class_weights = torch.FloatTensor([len(y_train) / (6 * c) for c in class_counts])
print(f"Class weights: {class_weights}")

# DataLoader — Conv2d expects (N, C, H, W) = (N, 3, 30, 15)
X_train_t = torch.from_numpy(X_train).float()
y_train_t = torch.from_numpy(y_train).long()
X_test_t = torch.from_numpy(X_test).float()
y_test_t = torch.from_numpy(y_test).long()

batch_size = 16
train_loader = DataLoader(TensorDataset(X_train_t, y_train_t), batch_size=batch_size, shuffle=True)
test_loader = DataLoader(TensorDataset(X_test_t, y_test_t), batch_size=batch_size, shuffle=False)
print(f"Batches per epoch: {len(train_loader)}")

Found 3895 wav files in ./studio_data
Features: (3895, 1350)  Labels: (3895,)
Reshaped for Conv2d: (3895, 3, 30, 15)
Train: (3116, 3, 30, 15)  Test: (779, 3, 30, 15)
Class weights: tensor([1.0223, 0.9653, 1.0026, 1.0203, 1.0183, 0.9744])
Batches per epoch: 195


In [0]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        # Block 1: (3, 30, 15) -> pool -> (32, 15, 7)
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(32)
        self.pool1 = nn.MaxPool2d(2)

        # Block 2: (32, 15, 7) -> pool -> (64, 7, 3)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(64)
        self.pool2 = nn.MaxPool2d(2)

        # Block 3: (64, 7, 3) -> pool -> (128, 3, 1)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.bn3 = nn.BatchNorm2d(128)
        self.pool3 = nn.MaxPool2d(2)

        self.dropout = nn.Dropout(0.25)   # reduced from 0.4 — train<test means over-regularization
        self.fc1 = nn.Linear(128 * 3 * 1, 64)   # 384 -> 64
        self.fc2 = nn.Linear(64, 6)
        self.logsoftmax = nn.LogSoftmax(dim=1)

    def forward(self, x):
        x = self.pool1(F.relu(self.bn1(self.conv1(x))))
        x = self.dropout(x)
        x = self.pool2(F.relu(self.bn2(self.conv2(x))))
        x = self.dropout(x)
        x = self.pool3(F.relu(self.bn3(self.conv3(x))))
        x = self.dropout(x)
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.logsoftmax(self.fc2(x))
        return x

print(Net())

Net(
  (conv1): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (bn1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)
  (pool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)
  (pool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv3): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (bn3): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)
  (pool3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (dropout): Dropout(p=0.25, inplace=False)
  (fc1): Linear(in_features=384, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=6, bias=True)
  (logsoftmax): LogSoftmax(dim=1)
)


In [0]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Training on: {device}")

model = Net().to(device)
# Fine-tune from saved weights (dropout change doesn't affect state_dict)
model.load_state_dict(torch.load(model_path, map_location=device, weights_only=True))
class_weights_gpu = class_weights.to(device)

criterion = nn.NLLLoss(weight=class_weights_gpu)
optimizer = optim.Adam(model.parameters(), lr=0.001)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='min', factor=0.5, patience=3   # patience 5->3
)

num_epochs = 70
for epoch in range(num_epochs):
    model.train()
    running_loss, correct, total = 0.0, 0, 0

    for data, target in train_loader:
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * data.size(0)
        _, predicted = torch.max(output, 1)
        correct += (predicted == target).sum().item()
        total += target.size(0)

    epoch_loss = running_loss / total
    epoch_acc = 100.0 * correct / total
    scheduler.step(epoch_loss)

    if (epoch + 1) % 10 == 0 or epoch == 0:
        print(f"Epoch [{epoch+1:2d}/{num_epochs}]  Loss: {epoch_loss:.4f}  "
              f"Acc: {epoch_acc:.2f}%  LR: {optimizer.param_groups[0]['lr']:.6f}")

Training on: cpu
Epoch [ 1/70]  Loss: 0.3005  Acc: 89.44%  LR: 0.001000
Epoch [10/70]  Loss: 0.2199  Acc: 92.94%  LR: 0.001000


In [0]:
model.eval()
all_preds, all_targets = [], []

with torch.no_grad():
    for data, target in test_loader:
        data, target = data.to(device), target.to(device)
        output = model(data)
        _, predicted = torch.max(output, 1)
        all_preds.extend(predicted.cpu().numpy())
        all_targets.extend(target.cpu().numpy())

test_acc = 100.0 * sum(p == t for p, t in zip(all_preds, all_targets)) / len(all_targets)
print(f"Test Accuracy: {test_acc:.2f}%\n")

cm = confusion_matrix(all_targets, all_preds)
print("Confusion Matrix (rows=true, cols=predicted):")
print(cm)
print()
print(classification_report(all_targets, all_preds, digits=3,
                            target_names=[f"digit_{i}" for i in range(6)]))
print("Train class counts:", collections.Counter(y_train.tolist()))
print("Test class counts: ", collections.Counter(y_test.tolist()))

Test Accuracy: 91.01%

Confusion Matrix (rows=true, cols=predicted):
[[117   0   8   0   1   1]
 [  3 117   4   0   6   4]
 [  3   1 113   1   8   3]
 [  4   0   0 120   1   2]
 [  1   0   3   1 121   2]
 [  3   5   1   2   2 121]]

              precision    recall  f1-score   support

     digit_0      0.893     0.921     0.907       127
     digit_1      0.951     0.873     0.911       134
     digit_2      0.876     0.876     0.876       129
     digit_3      0.968     0.945     0.956       127
     digit_4      0.871     0.945     0.906       128
     digit_5      0.910     0.903     0.906       134

    accuracy                          0.910       779
   macro avg      0.911     0.911     0.910       779
weighted avg      0.912     0.910     0.910       779

Train class counts: Counter({1: 538, 5: 533, 2: 518, 4: 510, 3: 509, 0: 508})
Test class counts:  Counter({1: 134, 5: 134, 2: 129, 4: 128, 0: 127, 3: 127})


In [0]:
model_path = '/Workspace/Users/balga@vestas.com/Phyton/Phyton_IIT/Hacktron_Sep/studio_model.t7'
torch.save(model.state_dict(), model_path)
print(f"Model saved to {model_path}")

Model saved to /Workspace/Users/balga@vestas.com/Phyton/Phyton_IIT/Hacktron_Sep/studio_model.t7


## Stage 2: Fine-tune on Studio + Team Data

Collect team voice samples via the server, then combine with studio data and fine-tune.

In [0]:
# Download team data (replace YOUR_GROUP_ID with actual ID from lab)
# !wget -r -A .wav https://aiml-sandbox1.talentsprint.com/audio_recorder/<YOUR_GROUP_ID>/team_data/ -nH --cut-dirs=100 -P ./team_data

team_features, team_labels = load_data('./team_data')
print(f"Team data: {team_features.shape}")

# Combine studio + team, reshape for Conv2d
combined_features = np.vstack((studio_features, team_features)).reshape(-1, 3, 30, 15)
combined_labels = np.concatenate((studio_labels, team_labels))
print(f"Combined: {combined_features.shape}")

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    combined_features, combined_labels,
    test_size=0.2, random_state=42, stratify=combined_labels
)

train_loader_c = DataLoader(
    TensorDataset(torch.from_numpy(X_train_c).float(), torch.from_numpy(y_train_c).long()),
    batch_size=16, shuffle=True
)
test_loader_c = DataLoader(
    TensorDataset(torch.from_numpy(X_test_c).float(), torch.from_numpy(y_test_c).long()),
    batch_size=16, shuffle=False
)
print(f"Combined batches per epoch: {len(train_loader_c)}")

In [0]:
# Fine-tune from studio-trained weights with smaller LR
model.load_state_dict(torch.load(model_path, map_location=device, weights_only=True))
model = model.to(device)
criterion_c = nn.NLLLoss()
optimizer_c = optim.Adam(model.parameters(), lr=0.0001)

for epoch in range(20):
    model.train()
    running_loss, correct, total = 0.0, 0, 0
    for data, target in train_loader_c:
        data, target = data.to(device), target.to(device)
        optimizer_c.zero_grad()
        output = model(data)
        loss = criterion_c(output, target)
        loss.backward()
        optimizer_c.step()
        running_loss += loss.item() * data.size(0)
        _, predicted = torch.max(output, 1)
        correct += (predicted == target).sum().item()
        total += target.size(0)
    if (epoch + 1) % 5 == 0:
        print(f"Epoch [{epoch+1}/20]  Loss: {running_loss/total:.4f}  Acc: {100*correct/total:.2f}%")

In [0]:
model.eval()
correct, total = 0, 0
with torch.no_grad():
    for data, target in test_loader_c:
        data, target = data.to(device), target.to(device)
        output = model(data)
        _, predicted = torch.max(output, 1)
        correct += (predicted == target).sum().item()
        total += target.size(0)

print(f"Combined Test Accuracy: {100.0 * correct / total:.2f}%")

team_model_path = '/Workspace/Users/balga@vestas.com/Phyton/Phyton_IIT/Hacktron_Sep/studio_team_model.t7'
torch.save(model.state_dict(), team_model_path)
print(f"Model saved to {team_model_path}")