# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

## Tensor basics

### Setup Steps

In [ ]:
!pip3 install torch

In [ ]:
import torch
import numpy as np

In [ ]:
print(torch.__version__)

2.9.0+cu126


#**Tensor**

###Initializing a tensor

In [ ]:
# Initializing a tensor
a = torch.Tensor([2,3,4])
print(a.size())
print(a)

torch.Size([3])
tensor([2., 3., 4.])


In [ ]:
a.type()

'torch.FloatTensor'

In [ ]:
t = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(t)
print(t.size())
print(t.t())

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Creating a scalar tensor

In [ ]:
a = torch.tensor(200)
print(a)
print(a.size())
print(a.type())

tensor(200)
torch.Size([])
torch.LongTensor


###Converting scalar Tensor to python number

In [ ]:
print(a.item())
print(type(a.item()))

200
<class 'int'>


###Creating a float tensor

In [ ]:
a = torch.tensor([2.0,3])
a.type()

'torch.FloatTensor'

###Providing the data type while creating the tensor

In [ ]:
a = torch.tensor([2,3],dtype=torch.int32)
a.type()

'torch.IntTensor'

###Just like numpy, creating a tensor by copying another tensor results, pointing to same memory location









In [ ]:
a = torch.tensor([2.0, 3])
b = a
c=a.clone()
b[0] = 11
print(a)
print(b)
print(c)

tensor([11.,  3.])
tensor([11.,  3.])
tensor([2., 3.])


###2D tensor

In [ ]:
a = torch.tensor([[1,2],[3,4]])
print(a)
print(a.type())

tensor([[1, 2],
        [3, 4]])
torch.LongTensor


In [ ]:
a = torch.Tensor([[1,2],[3,4]])
print(a)
print(a.type())

tensor([[1., 2.],
        [3., 4.]])
torch.FloatTensor


###Creating and initializing a tensor with random values

In [ ]:
a = torch.rand(3,4)
print(a)

tensor([[0.6777, 0.5758, 0.7747, 0.9909],
        [0.4872, 0.8130, 0.9590, 0.3057],
        [0.6248, 0.2029, 0.3250, 0.7563]])


###Creating and initializing a float tensor with zeros

In [ ]:
a = torch.zeros((4,5), dtype=torch.float32)
print(a)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


###Creating an Identity tensor

In [ ]:
a = torch.eye(4,4)
print(a)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


#**Tensor Operations**

###Addition of two tensor

In [ ]:
x = torch.rand(3,3)
y = torch.rand(3,3)
z = x+y
print(z)

tensor([[1.6550, 1.6849, 0.7970],
        [0.4502, 1.5792, 1.3824],
        [0.6393, 1.1111, 1.1291]])


###Addition of two tensor (alternative)

In [ ]:
z = x.add(y)
print(z)
#z=x+y

tensor([[1.6550, 1.6849, 0.7970],
        [0.4502, 1.5792, 1.3824],
        [0.6393, 1.1111, 1.1291]])


###Inplace addition of two tensor

In [ ]:
print(x)
x.add_(y)
#x=x+y

print(x)

tensor([[0.9628, 0.8149, 0.6726],
        [0.3112, 0.6407, 0.7096],
        [0.6359, 0.6967, 0.2941]])
tensor([[1.6550, 1.6849, 0.7970],
        [0.4502, 1.5792, 1.3824],
        [0.6393, 1.1111, 1.1291]])


In [ ]:
c=torch.tensor(20)
print(c.size())
c=torch.tensor([20])
print(c.size())
c=torch.tensor([[20]])
print(c.size())
c=torch.tensor([[[20]]])
print(c.size())

torch.Size([])
torch.Size([1])
torch.Size([1, 1])
torch.Size([1, 1, 1])


###Element wise multiplication

In [ ]:
print(x*y)

tensor([[1.1455, 1.4658, 0.0991],
        [0.0626, 1.4820, 0.9299],
        [0.0021, 0.4605, 0.9429]])


###Matrix multiplication

In [ ]:
z = torch.matmul(x,y)
print(z)
z.size()

tensor([[1.3824, 3.3513, 2.0047],
        [0.5358, 2.4466, 2.2726],
        [0.6007, 2.0668, 1.7698]])


torch.Size([3, 3])

###Reshaping tensors

In [ ]:
x = torch.rand(5,6)
print("Size of x :\n",x.size())
print("x:\n",x)
y = x.view(30)
print("Size of y :\n",y.size())
print("y:\n",y)
z = x.view(3,10)
print("Size of z :\n",z.size())
print("z:\n",z)
z = x.view(-1,10)
print("Size of z :\n",z.size())
print("z:\n",z)

Size of x :
 torch.Size([5, 6])
x:
 tensor([[0.0803, 0.6668, 0.3526, 0.6662, 0.9223, 0.4814],
        [0.5547, 0.7389, 0.0973, 0.7380, 0.9512, 0.1526],
        [0.7274, 0.5532, 0.2898, 0.8639, 0.6020, 0.5283],
        [0.3382, 0.0531, 0.0554, 0.1008, 0.6271, 0.5170],
        [0.3111, 0.9041, 0.3923, 0.0843, 0.8472, 0.9716]])
Size of y :
 torch.Size([30])
y:
 tensor([0.0803, 0.6668, 0.3526, 0.6662, 0.9223, 0.4814, 0.5547, 0.7389, 0.0973,
        0.7380, 0.9512, 0.1526, 0.7274, 0.5532, 0.2898, 0.8639, 0.6020, 0.5283,
        0.3382, 0.0531, 0.0554, 0.1008, 0.6271, 0.5170, 0.3111, 0.9041, 0.3923,
        0.0843, 0.8472, 0.9716])
Size of z :
 torch.Size([3, 10])
z:
 tensor([[0.0803, 0.6668, 0.3526, 0.6662, 0.9223, 0.4814, 0.5547, 0.7389, 0.0973,
         0.7380],
        [0.9512, 0.1526, 0.7274, 0.5532, 0.2898, 0.8639, 0.6020, 0.5283, 0.3382,
         0.0531],
        [0.0554, 0.1008, 0.6271, 0.5170, 0.3111, 0.9041, 0.3923, 0.0843, 0.8472,
         0.9716]])
Size of z :
 torch.Size([3, 10]

###Generating Numbers in Sequence

In [ ]:
x = torch.arange(9)
print(x)
x = x.view(3,3)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


###Concatenating two tensors at a given dimension

In [ ]:
print(torch.cat((x,x),dim=0))
print(torch.cat((x,x),dim=1))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5],
        [6, 7, 8, 6, 7, 8]])


###Reducing the redundant dimension by squeeze operation

In [ ]:
x1= torch.rand(1,5)
print("size of x1 squeezing:\n",x1.size())
print(x1)
x1 = x1.squeeze()
print("size of x1 after squeezing:\n", x1.size())
print(x1)

size of x1 squeezing:
 torch.Size([1, 5])
tensor([[0.7141, 0.5909, 0.4895, 0.8446, 0.9221]])
size of x1 after squeezing:
 torch.Size([5])
tensor([0.7141, 0.5909, 0.4895, 0.8446, 0.9221])


In [ ]:
x1 = torch.rand(1,1,5)
print("size of x1 before squeezing:\n", x1.size())
print(x1)
x1 = x1.squeeze()
print("size of x1 after squeezing:\n", x1.size())
print(x1)
print(x1.numpy())

size of x1 before squeezing:
 torch.Size([1, 1, 5])
tensor([[[0.4838, 0.0321, 0.8741, 0.7107, 0.9543]]])
size of x1 after squeezing:
 torch.Size([5])
tensor([0.4838, 0.0321, 0.8741, 0.7107, 0.9543])
[0.483755   0.03214824 0.87405634 0.71066266 0.954271  ]


In [ ]:
x2 = torch.rand(3,1,4,1,5)
print("size of x2 before squeezing:\n", x2.size())
print(x2)
x2 = x2.squeeze()
print("size of x2 after squeezing:\n", x2.size())
print(x2)

size of x2 before squeezing:
 torch.Size([3, 1, 4, 1, 5])
tensor([[[[[0.8094, 0.8073, 0.9877, 0.1869, 0.5237]],

          [[0.0451, 0.6707, 0.3937, 0.0583, 0.6093]],

          [[0.4365, 0.8692, 0.3103, 0.3611, 0.4555]],

          [[0.5721, 0.9706, 0.1617, 0.9451, 0.9888]]]],



        [[[[0.5143, 0.9258, 0.9250, 0.5288, 0.7031]],

          [[0.9829, 0.7615, 0.7050, 0.4600, 0.6313]],

          [[0.9077, 0.7774, 0.3542, 0.2136, 0.9725]],

          [[0.9383, 0.4815, 0.5358, 0.2118, 0.7875]]]],



        [[[[0.9757, 0.9299, 0.3183, 0.0708, 0.9038]],

          [[0.1976, 0.7143, 0.2960, 0.4035, 0.0170]],

          [[0.5028, 0.5662, 0.3991, 0.9572, 0.0336]],

          [[0.5237, 0.8939, 0.9795, 0.2826, 0.6875]]]]])
size of x2 after squeezing:
 torch.Size([3, 4, 5])
tensor([[[0.8094, 0.8073, 0.9877, 0.1869, 0.5237],
         [0.0451, 0.6707, 0.3937, 0.0583, 0.6093],
         [0.4365, 0.8692, 0.3103, 0.3611, 0.4555],
         [0.5721, 0.9706, 0.1617, 0.9451, 0.9888]],

        [[0.514

###Extending the dimension by unsqueeze operation

In [ ]:
x = torch.rand(3,4,5,6)
print(x.size())
#print(x)
print(x.unsqueeze(dim=2).size())
#print(x.unsqueeze(dim=2))
print(x.unsqueeze(dim=3).size())
print(x.unsqueeze(dim=4).size())

torch.Size([3, 4, 5, 6])
torch.Size([3, 4, 1, 5, 6])
torch.Size([3, 4, 5, 1, 6])
torch.Size([3, 4, 5, 6, 1])


###Numpy Bridge
####Converting a numpy array to torch tensor

In [ ]:
x = np.array([[1.0,2],[3,4]])
print(type(x))
y = torch.from_numpy(x)
print(y)
y.type()

<class 'numpy.ndarray'>
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


'torch.DoubleTensor'

####Converting a torch tensor to numpy array

In [ ]:
z = y.numpy()
z.dtype

dtype('float64')

**CUDA Tensors**

####Checking the availability of CUDA/GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
# Linux bash command to print the status of nvidia gpu (memory and processes)
!nvidia-smi

Sat Jan 31 05:18:16 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   76C    P0             34W /   70W |     104MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

####Defining the device object (cpu/gpu)

In [ ]:
device = torch.device("cuda")
x = torch.rand(3,3)
print(x)
x.type()

tensor([[0.0961, 0.8905, 0.8835],
        [0.3197, 0.4675, 0.1359],
        [0.8555, 0.6102, 0.4656]])


'torch.FloatTensor'

In [ ]:
x = x.to(device)
x.type()

'torch.cuda.FloatTensor'


###Transferring the tensor to the respective device (here cpu->gpu)
####Transferring the tensor from gpu->cpu


In [ ]:
# Transferring the tensor from gpu->cpu
device_cpu = torch.device("cpu")
x = x.to(device_cpu)
x.type()

'torch.FloatTensor'

In [ ]:
import torch
from torch.autograd import Variable
N=100
D_in=10
H=100
D_out=1

x = Variable(torch.randn(N, D_in), requires_grad=False)
y = Variable(torch.randn(N, D_out), requires_grad=False)
w1 = Variable(torch.randn(D_in,H), requires_grad=True)
w2 = Variable(torch.randn(H, D_out), requires_grad=True)
b1 = Variable(torch.randn(H), requires_grad=True)
b2 = Variable(torch.randn(D_out), requires_grad=True)
learning_rate = 1e-5

for t in range(50000):
    y_pred = ((x.mm(w1)+b1).clamp(min=0).mm(w2)+b2) #FP
    loss = (y_pred-y).pow(2).sum() #Loss computation
    loss.backward() #BP
    w2.data -= learning_rate*w2.grad #WU
    w1.data -= learning_rate*w1.grad #WU
    b2.data -= learning_rate*b2.grad #WU
    b1.data -= learning_rate*b1.grad #WU
    w1.grad.data.zero_() #Reset gradients
    w2.grad.data.zero_() #Reset gradients
    b1.grad.data.zero_() #Reset gradients
    b2.grad.data.zero_() #Reset gradients
    if t%1000==0:
      print(loss)
      print(loss.type())

tensor(40861.0078, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(48.7891, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(12.2798, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(3.8130, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(1.3526, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(0.5341, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(0.2246, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(0.0977, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(0.0435, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(0.0197, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(0.0091, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(0.0042, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(0.0020, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(0.0009, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(0.0004, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(0.0002, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(0.0001, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(6.8045e-05, grad_f